name: acnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - h5py>=3.0.0
  - pillow>=8.0.0
  - rdkit>=2022.3.0
  - mdtraj>=1.9.0
  - pdbfixer>=1.8.0
  - openmm>=7.7.0
  - qiskit>=0.39.0,<1.0.0
  - qiskit-machine-learning>=0.5.0,<1.0.0
  - tensorflow>=2.8.0
  - pip
  - pip:
    - tensorflow>=2.8.0
    - deepchem>=2.6.0
