#!/usr/bin/env python
"""
Extract 10-dim fc1 features from the trained 3DCNN model.

Run AFTER generate_mlhdf_rdkit.py has created the ML-HDF file.

Steps performed:
  1. Load ML-HDF (generated by generate_mlhdf_rdkit.py)
  2. For each complex: voxelize atoms → 19x48x48x48 volume → gaussian filter
  3. Run forward pass through trained 3DCNN → save fc1_z (10-dim)
  4. Save as NPZ:  {pdbid: array(10,)}

Usage:
    python extract_3dcnn_features.py \
        --hdf    C:/bindingaffinity/FAST-master/model/quantum_fusion/refined_all.hdf \
        --ckpt   C:/bindingaffinity/FAST-master/model/3dcnn/checkpoint_3dcnn_refined/best_checkpoint.pth \
        --output C:/bindingaffinity/FAST-master/model/quantum_fusion/refined_3dcnn_features.npz
"""

import os
import sys
import argparse

# ── make 3dcnn code importable ──────────────────────────────────────────────
_3DCNN_DIR = os.path.join(os.path.dirname(__file__), "..", "3dcnn")
sys.path.insert(0, os.path.abspath(_3DCNN_DIR))

import h5py
import numpy as np
import torch
from tqdm import tqdm

from model import Model_3DCNN, strip_prefix_if_present
from img_util import GaussianFilter, voxelize_batch


def extract(hdf_path: str, ckpt_path: str, output_path: str,
            batch_size: int = 32, max_atoms: int = 2000):
    """
    Extract 10-dim 3DCNN features for every complex in *hdf_path*.
    """
    use_cuda = torch.cuda.is_available()
    device = torch.device("cuda:0" if use_cuda else "cpu")
    print(f"Using device: {device}")

    # ── load checkpoint ──────────────────────────────────────────────────────
    print(f"Loading 3DCNN checkpoint: {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
    state = ckpt["model_state_dict"]
    strip_prefix_if_present(state, "module.")

    model = Model_3DCNN(use_cuda=use_cuda, verbose=0)
    model.load_state_dict(state, strict=False)
    model.to(device)
    model.eval()
    print(f"  {sum(p.numel() for p in model.parameters())} parameters")

    gfilter = GaussianFilter(dim=3, channels=19, kernel_size=5, sigma=1,
                             use_cuda=use_cuda)
    if use_cuda:
        gfilter = gfilter.to(device)

    # ── load all complexes into memory ───────────────────────────────────────
    feat_dict: dict = {}
    pdbids_all, arrays_all = [], []
    with h5py.File(hdf_path, "r") as hf:
        pdbids = list(hf.keys())
        print(f"Processing {len(pdbids)} complexes from {hdf_path}")
        for pdbid in tqdm(pdbids, desc="Loading HDF"):
            try:
                ds = hf[pdbid]["pybel"]["processed"]["pdbbind"]["data"]
                raw = np.array(ds, dtype=np.float32)   # (N, 22)
            except KeyError:
                continue
            n = min(raw.shape[0], max_atoms)
            x = np.zeros((max_atoms, raw.shape[1]), dtype=np.float32)
            x[:n] = raw[:n]
            pdbids_all.append(pdbid)
            arrays_all.append(x)

    # ── batched GPU inference ─────────────────────────────────────────────────
    n_total = len(pdbids_all)
    for start in tqdm(range(0, n_total, batch_size), desc="3DCNN features"):
        end = min(start + batch_size, n_total)
        batch_ids = pdbids_all[start:end]
        batch_np  = np.stack(arrays_all[start:end], axis=0)  # (B, N, 22)
        x_t = torch.from_numpy(batch_np).to(device)          # (B, N, 22)

        with torch.no_grad():
            with torch.autocast(device_type='cuda', enabled=use_cuda):
                vol = voxelize_batch(x_t[:, :, :3], x_t[:, :, 3:])  # (B,19,48,48,48)
                vol = gfilter(vol)
                _, fc1_z = model(vol)   # fc1_z: (B, 10)

        fc1_np = fc1_z.float().cpu().numpy()  # (B, 10)
        for i, pid in enumerate(batch_ids):
            feat_dict[pid] = fc1_np[i]        # (10,)

    # ── save ─────────────────────────────────────────────────────────────────
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    np.savez(output_path, **feat_dict)
    print(f"\nSaved {len(feat_dict)} feature vectors to {output_path}")
    if feat_dict:
        sample = next(iter(feat_dict.values()))
        print(f"  Feature shape: {sample.shape}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extract 3DCNN fc1 features (10-dim) from ML-HDF"
    )
    parser.add_argument(
        "--hdf",
        default="C:/bindingaffinity/FAST-master/model/quantum_fusion/refined_all.hdf",
        help="ML-HDF file (output of generate_mlhdf_rdkit.py)",
    )
    parser.add_argument(
        "--ckpt",
        default="C:/bindingaffinity/FAST-master/model/3dcnn/checkpoint_3dcnn_refined/best_checkpoint.pth",
        help="trained 3DCNN checkpoint (.pth)",
    )
    parser.add_argument(
        "--output",
        default="C:/bindingaffinity/FAST-master/model/quantum_fusion/refined_3dcnn_features.npz",
        help="output NPZ file",
    )
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument(
        "--max-atoms", type=int, default=2000,
        help="max atoms per complex (excess truncated)",
    )
    args = parser.parse_args()

    os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

    extract(
        hdf_path=args.hdf,
        ckpt_path=args.ckpt,
        output_path=args.output,
        batch_size=args.batch_size,
        max_atoms=args.max_atoms,
    )
